### ISSUE TITLE
Editor: RUN ERROR: Error on animation 1/new: Attempted to divide by zero.

### ISSUE THREAD

**Issue by skeddles** [Adrianotiger/desktopPet#64]
No idea what this error means or how to fix it. My animation isn't even called new anymore. Happens when I try to run the test.

**Comment by skeddles** [comment]
Restarting the app made this go away, but I had to fix a lot of things that didn't seem to save on the animation.

**Comment by Adrianotiger** [comment]
Hi,
It could be that you don't have any sprite on the animation 1?
You can send me the xml if you want, and I will check it and improve the editor.

**Comment by skeddles** [comment]
After restarting I no longer see that message, and there were 2 frames instead of the 8 that I added, so I'm not sure what was wrong but I don't think the error is in my xml, just a temporary program error. I don't really expect it to be fixed with so little info, but maybe the error message could be a little more clear, like what is set to 0 that it's trying to divide by.

**Comment by skeddles** [comment]
Now I'm getting this when I try to compile on "verify internal links"

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PetEditor.XmlTools.EvalValue(String parsingText, StatisticsDataInput dimensions, Control control)
   at PetEditor.Tools.button3_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

And this seems to persist between restarting the editor. 

Here is my xml: https://gist.github.com/skeddles/912de333c6934cde3b02863241905d6e

**Comment by Adrianotiger** [comment]
Hi Skeddles,
I can't reproduce it with the editor (v.0.4). But there are some bugs on the editor, I know. I am trying to remove them so that the editor is more stable.
I saw, that you used the magenta as background. As it is a png, you can use a transparent color. The application will replace it with magenta.

**Comment by Adrianotiger** [comment]
I uploaded the new editor (0.5). Can you check if it is solved?
